### ISSUE TITLE
Domain が code for

### ISSUE THREAD

**Issue by tsukumonasu** [BlockchainTokai/ethClientSample#1]
IOTに変えるべきでは？

https://github.com/BlockchainTokai/ethClientSample/blob/75ec036004a19b5e11d7588754c69d26fedbd37b/src/main/java/nagoya/code4/App.java#L1

**Comment by kouichiUme** [comment]
nagoya.iotに変更しました。

**Comment by tsukumonasu** [comment]
以下にて修正済み
75ec036004a19b5e11d7588754c69d26fedbd37b
